# Note: Do not edit this file, if you want to override a variable
# do it in your configuration file before you include this file

# Cyclops Tensor Framework ====================================================
CTF_PATH    ?= lib/build/${CONFIG}/ctf
CTF_LIB     ?= -L${CTF_PATH}/lib -lctf
CTF_INCLUDE ?= -I${CTF_PATH}/include

# yaml-cpp ====================================================================
YAML_PATH    ?= lib/build/${CONFIG}/yaml-cpp
YAML_LIB     ?= -L${YAML_PATH} -lyaml-cpp
YAML_INCLUDE ?= -I${YAML_PATH}/include

# BLAS ========================================================================
BLAS_INCLUDE ?= -I${BLAS_PATH}/include
BLAS_LIB     ?= -L${BLAS_PATH}/lib -lopenblas

# ScaLAPACK ===================================================================
SCALAPACK_LIB ?= -L${SCALAPACK_PATH}/lib -lscalapack
