#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Alejandro Gallo.
# url: github.com/alejandrogallo
# License: 2018, GPLv3.
# Email: aamsgallo@gmail.com

import argparse
import sys
import json
try:
    import yaml
except:
    print('Try installinng python yaml, pip install pyyaml')
    sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawTextHelpFormatter,
        description="Convert json into yaml")
    parser.add_argument("input_file", help= "Input file.", action="store")
    args = parser.parse_args()
    with open(args.input_file) as f:
        print(yaml.dump(json.load(f),
                        allow_unicode=True,
                        default_flow_style=False))
